apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-server-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - name: ubuntu
        image: ubuntu:latest
        command: ["/bin/bash", "-c", "tail -f /dev/null"]
        volumeMounts:
        - name: shared-data
          mountPath: /sharedd  # Path inside the container
      volumes:
      - name: shared-data
        hostPath:
          path: "/mnt/d_drive/test-dir"
          type: Directory


